.TH HPT 1 "High Portable Tosser (v0.21)"
.SH NAME
hpt \- toss pkt files to squish/msg bases and export messages
.SH SYNTAX
.TP
.B Toss pkt files from inbound
hpt toss
.br
.TP
.B Scan messages
hpt scan
.TP
.SH DESCRIPTION
High Portable Tosser is the way to toss your fidonet mail.
.SH BUGS
I suppose there are :). So, report me, if you found any.
hint: if there is a core files after first tryes to run HPT - don't worry!
Just edit /etc/fido/config. 99% of troubles in wrong config file.
.SH AUTHOR
Matthias Tichy (mtt@uni-paderborn.de).
