# Solaris Sparc/Intel makefile
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
RM     =rm
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG)
LFLAGS =$(DEBUG)
CDEFS  =-DUNIX
CC     =gcc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/libfidoconfigsun.a ../../smapi/libsmapisun.a

include ../makefile.inc



