.TH HPT 1 "Highly Portable Tosser (v1.1.0)"
.SH NAME
hpt \- toss pkt files to squish/msg/jam bases and export messages
.SH SYNTAX
.TP
.B Toss pkt files from inbound
hpt toss
.br
.TP
.B Toss messages from badarea (force)
hpt toss -b[f]
.br
.TP
.B Scan echomail messages
hpt scan
.br
.TP
.B Scan echomail messages without HighWaters of position
hpt scan -w
.br
.TP
.B Scan echomail messages from alternative echotoss file
hpt scan -f <echotoss.log>
.br
.TP
(see info hpt for more details)
.br
.TP
.B Scan echomail messages from areas matching <pattern>
hpt scan -a <pattern>
.br
.TP
.B Pack netmail messages
hpt pack
.br
.TP
.B Links echomail messages
hpt link [areamask]
.br
.TP
.B Process areafix
hpt afix [<addr> command]
hpt qupd - update queue file and do some areafix jobs
hpt qrep - make report based on information from queue file
hpt qrep -d - print info described above, but show only changes
.br
.TP
.B Post a message to area
hpt post [options] file

options are:
.TP 1i
\fB \ \ \ \ \ \ \-nf "name from"
message sender's name, if not included \fBpost\fP use sysop name (see \fBfidoconfig\fP) 
.TP 1i
\fB \ \ \ \ \ \ \-nt "name to"
message receiver's name, if not included \fBpost\fP use "All"
.TP 1i
\fB \ \ \ \ \ \ \-af "address from"
message sender's address, if not included \fBpost\fP use first system address (see \fBfidoconfig\fP)
.TP 1i
\fB \ \ \ \ \ \ \-at "address to"
message receiver's address, \fB*MUST BE PRESENT*\fP
.TP 1i
\fB \ \ \ \ \ \ \-s "subject"
subject line, if not included then assumed to be empty
.TP 1i
\fB \ \ \ \ \ \ \-e "echo area"
area to post echomail message into, if not included message is posted to netmail
.TP 1i
\fB \ \ \ \ \ \ \-z "tearline"
tearline, if not included then assumed to be empty line
.TP 1i
\fB \ \ \ \ \ \ \-o "origin"
origin, if not included then assumed to be name of station in config-file
.TP 1i
\fB \ \ \ \ \ \ \-f flag(s)
flags to set to the posted msg. possible ones are:
pvt, crash, read, sent, att, fwd, orphan, k/s, loc, 
hld, xx2,  frq, rrq, cpt, arq, urq;
use it without trailing brackets like this: pvt loc k/s
.TP 1i
\fB \ \ \ \ \ \ -x\fP export message to echo links
.TP 1i
\fB \ \ \ \ \ \ -d\fP erase input file after posting
.TP 1i
\fB \ \ \ \ \ \ -u[size] uue-multipart posting
size - number of lines per section(150 for default)
.TP 1i
\fB \ \ \ \ \ \ -h\fP get help
.TP 1i
\fB \ \ \ \ \ \ file\fP - text file to post into echo or "-" for stdin
.br
.TP
.B Refresh area subscription
hpt relink <addr>
.br
.TP
.B Set pause for links who don't poll our system
hpt pause
.br
.TP
.B Quiet mode (no screen output)
hpt -q
.br
.TP
.B Set config-file name, if needed
hpt -c /path/to/config
.SH DESCRIPTION
Highly Portable Tosser is the way to toss your fidonet mail.
.SH BUGS
I suppose there are :). So, report me, if you found any.
Every time you changed the config-file please run tparser to see if 
your config is valid...
.SH AUTHORS
1997-1999: Matthias Tichy, 2:2432/645 (mtt@tichy.de)
.br
1999-2002: Max Levenkov, 2:5000/117 (sackett@mail.ru)
