.TH HPTLINK 1 "10 Dec 1999"
.SH NAME
hptlink \- messages linker for hpt
.SH SYNTAX
.B hptlink
[\-t] [\-s] [\-a] [\-r] [\-l loglevel] [\-n] [areaname ...]
.TP
.B \-t
build reply TREE
.TP
.B \-s
do not use Subject
.TP
.B \-a
search in all messages (for singlethread only)
.TP
.B \-r
do not use REPLY:/MSGID:
.TP
.B \-n
Link with 'new' messages only ('new' start from last linked + 1). Great speedup
in repeated linkings, but doesn't relink anything already linked.

.SH DESCRIPTION
hptlink links messages in areas specified by arguments \fIareaname\fP.
Area list can be obtained from \fIimportlog\fP file when \fILinkWithImportlog\fP
isn't set to \fI'no'\fP.
All areas are linked when \fIimportlog\fP file doesn't exist and no \fIareaname\fP
are set by arguments.

.SH FILES
.I /path/to/config
The husky config file.
.sp 1
.I hpt.log
Log file, shared with hpt. Placed into "logfiledir" directory defined in config file.
.sp 1
.I importlog
List of areas for linking.

.SH SEE ALSO
hpt(1), info fidoconfig

.SH AUTORS
Serguei Revtov 2:5021/11.10 or/and 2:5021/19.1
.sp 1
Kolya Nesterov
.sp 1
other members of the Husky developers team.

