.TH HPTTREE 1 "08 Jan 2000"
.SH NAME
hpttree \- area distribution tree builder for hpt
.SH SYNTAX
.B hpttree
[\-p] [areaname ...]
.TP
.B \-p
toggle pseudographics mode. Default for UNIXs is do not use pseudographic
character, and use that ones on other platforms

.SH DESCRIPTION
hpttree prints distribution tree of areas specified by arguments \fIareaname\fP.
