.TH PKTINFO 1 "pktinfo" "05 April 2001" "Husky - Portable Fidonet Software"
.SH NAME
pktinfo \- Gives some Info about a Packet
.SH SYNOPSIS
.B pktinfo
[-h] [-t] <pktNames>
.SH "DESCRIPTION"
.B pktinfo
gives some Info about the Packets.
.br
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B -h
display msg header information (from/to/subject)
.br
.B -t
display msg text
.br
.B <pktNames>
Packets to process
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.physcip.uni-stuttgart.de/team.html.
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).

