# DJGPP makefile
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

.SUFFIXES:
.SUFFIXES: .c .obj

OBJ    =.obj
EXE    =.exe
RM     =cmd /c del
DIRSEP =/
CFLAGS =-Zomf -I../h -I../.. -c -O3 $(DEBUG)
LFLAGS =-Zomf -Zsys $(DEBUG)
CDEFS  =-DOS2
CC     =gcc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/fconfemo.lib ../../smapi/smapiemo.lib

include ../makefile.inc



