# EMX A.OUT STYLE MAKEFILE (REQ. EMXRT.DLL)
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
EXE    =.exe
RM     =cmd /c del
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG) -Wall -Wno-char-subscripts -funsigned-char
LFLAGS =-Zcrtdll $(DEBUG)
CDEFS  =-DOS2
CC     =gcc
EXENAMEFLAG=-o
SRC_DIR=../src/
LIBS   =../../fidoconf/fconfemx.a ../../smapi/smapiemx.a

include ../makefile.inc



