# DJGPP makefile
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
EXE    =.exe
RM     =del
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG) -Zwin32
LFLAGS =$(DEBUG) -Zwin32
CDEFS  =-DNT -D__NT__ -DWINNT
CC     =gcc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/fconfrxw.a ../../smapi/smapirxw.a

include ../makefile.inc



