# Mingw32 CPD makefile for crosscompiling for NT under Unix
# no support for the husky build environment

DEBUG=
# set to -g for debugging, NEVER use -s !!!

OBJ    =.o
EXE    =.exe
RM     =rm
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG)
LFLAGS =$(DEBUG)
CDEFS  =-DNT -D__NT__ -DWINNT
CC     =i386-mingw32-gcc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/libfidoconfigmgw.a ../../smapi/libsmapimgw.a -luser32

include ../makefile.inc



