# Generic UNIX makefile
# this file requires GNU make
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
RM     =rm
DIRSEP =/
CFLAGS =-I../h -I../.. -c  $(DEBUG)
LFLAGS =$(DEBUG)
CDEFS  =-DUNIX
CC     =cc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/libfidoconfigunix.a ../../smapi/libsmapiunix.a

include ../makefile.inc



