
DEBUG=
# set to -g for debugging, NEVER use -s !!!

CC=gcc
RM=del

CDEFS=-D__NT__ 
CFLAGS=-I../h -I../.. -c -Wall -O3 $(DEBUG)
LFLAGS=$(DEBUG)

EXENAMEFLAG=-o 
SRC_DIR=../src/
OBJ=.o
EXE=.exe

LIBS=-L../../smapi -L../../fidoconf -lfidoconfigmgw -lsmapimgw -luser32

default: all

%$(OBJ): $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $(CDEFS) $(SRC_DIR)$*.c

include makefile.inc

all: commonprogs

clean: commonclean

distclean: commondistclean
