# Generic UNIX makefile
#

DEBUG=-s
# set to -g for debugging

PERL=0
include makeperl.inc

CC=cc
EXENAMEFLAG=-o 
SRC_DIR=../src/
CFLAGS=-I../h -I../.. -c -O3 $(DEBUG) $(PERLFLAGS)
LFLAGS=$(DEBUG)
CDEFS =-DUNIX

OBJ=.o
RM=rm

LIBS=../../fidoconf/libfidoconfigunix.a ../../smapi/libsmapiunix.a

default: all

%$(OBJ): $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $(CDEFS) $(SRC_DIR)$*.c

include makefile.inc

all: commonprogs

clean: commonclean

distclean: commondistclean
