# DEC UNIX DEC CC makefile (for gcc, use makefile.unx)
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
RM     =rm
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG)
LFLAGS =$(DEBUG)
CDEFS  =-DUNIX
CC     =cc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/libfidoconfigosf.a ../../smapi/libsmapiosf.a

include ../makefile.inc



