# DJGPP makefile
# no support for the husky build environment

DEBUG=-s
# set to -g for debugging

OBJ    =.o
EXE    =.exe
RM     =del
DIRSEP =/
CFLAGS =-I../h -I../.. -c -O3 $(DEBUG)
LFLAGS =$(DEBUG)
CDEFS  =-DMSDOS
CC     =gcc
EXENAMEFLAG=-o 
SRC_DIR=../src/
LIBS   =../../fidoconf/fconfdjg.a ../../smapi/smapidjg.a

include ../makefile.inc



