.TH HPT 1 "High Portable Tosser (v0.22)"
.SH NAME
hpt \- toss pkt files to squish/msg bases and export messages
.SH SYNTAX
.TP
.B Toss pkt files from inbound
hpt toss
.br
.TP
.B Scan messages
hpt scan
.SH DESCRIPTION
High Portable Tosser is the way to toss your fidonet mail.
.SH BUGS
I suppose there are :). So, report me, if you found any.
hint: if there is a core files after first tries to run HPT - don't worry!
Just edit /etc/fido/config. 99% of troubles in wrong config file.
Every time you changed the config-file please run tparser to see if 
your config is valid...
.SH AUTHOR
Matthias Tichy (mtt@uni-paderborn.de).
