# Linux legacy makefile
#

DEBUG=-s
# set to -g for debugging

CC=gcc
EXENAMEFLAG=-o
SRC_DIR=../src/
CFLAGS=-I../h -c -O3 $(DEBUG)
LFLAGS=$(DEBUG)
CDEFS =-DUNIX
OBJ=.o
RM=rm

LIBS=../../fidoconf/libfidoconfiglnx.a ../../smapi/libsmapilnx.a

include ../makefile.inc
