.TH PURGEDUPES 1 "purgeDupes (v0.29)"
.SH NAME
purgeDupes \- kills the old parts dupes files according to fidoconfig
.SH SYNTAX
.TP
.B purge dupes
purgeDupes
.SH DESCRIPTION
purgeDupes kills the old dupes which are in the dupesfiles. The parameter
are taken from fidoconfig
.SH BUGS
I suppose there are :). So, report me, if you found any.
hint: if there is a core files after first tries to run purgeDupes - don't worry!
Just edit /etc/fido/config. 99% of troubles comes from a wrong config file.
After that  please call tparser of the fidonet package to check your
config.
.SH AUTHOR
Matthias Tichy (mtt@uni-paderborn.de).
